
import Link from "next/link";
import { ChevronLeft } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-neutral-100 text-foreground max-w-lg mx-auto">
      <header className="bg-primary text-primary-foreground p-4 flex items-center gap-4 sticky top-0 z-10">
        <Link href="/login" className="text-white">
          <ChevronLeft className="w-6 h-6" />
        </Link>
        <h1 className="font-bold text-xl">Privacy Policy</h1>
      </header>
      <div className="p-6 space-y-4">
        <h2 className="text-2xl font-semibold">Privacy Policy</h2>
        <p>Last updated: August 30, 2025</p>
        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
        
        <h3 className="text-xl font-semibold pt-4">Interpretation and Definitions</h3>
        <h4 className="font-semibold">Interpretation</h4>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        <h4 className="font-semibold mt-2">Definitions</h4>
        <p>For the purposes of this Privacy Policy:
            <ul className="list-disc list-inside space-y-2 mt-2">
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to 9XBETCLUB.</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Application.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
        </p>

        <h3 className="text-xl font-semibold pt-4">Contact Us</h3>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc list-inside space-y-2 mt-2">
            <li>By email: support@9xbetclub.com</li>
        </ul>
      </div>
    </div>
  );
}
